version: "3.8"

services:
  db-produtos:
    image: postgres:16.2
    hostname: db
    container_name: "containerBancoDeDadosProdutos"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./../scriptBancoDeDados:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    restart: always