version: "3.8"

services:
  db-itens:
    image: postgres:16.2
    container_name: "containerBancoDeDadosItens"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./scriptBancoDeDados:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    restart: always
  app-itens:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: app-sistema-itens
    environment:
      POSTGRES_HOST: db-itens:5432
      JWT_SECRET: "segredoMaisSeguroDoMundo"
    ports:
      - "8081:8081"
    depends_on:
      - db-itens
    restart: always